name: debian
on:
  push:
    branches: [ main, pearl ]
  pull_request:
    branches: [ main, pearl ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj3 debootstrap/checkout!
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install ninja-build
    - run: make -kj3 qemu!
    - run: sudo apt-get install fakeroot
    - run: make -kj3 build/debootstrap/.stage1
    - run: make -kj3 artifacts/up/debootstrap-stage1.tar.gz
    - run: make -kj3 artifact-push!
