name: workflow
on:
  push:
    branches: [ main, pearl ]
  pull_request:
    branches: [ main, pearl ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./github/env/
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install dtc
    - run: make -kj3 oldconfig-linux/stage1!
    - run: make -kj3 oldconfig-linux/stage2!
    - run: make -kj3 oldconfig-linux/linux!
    - run: make -kj3 build/linux.image
    - run: make -kj3 build/stage2.image
    - run: make -kj3 build/stage1.image
    - run: make -kj3 artifacts/up/linux.image
    - run: make -kj3 artifacts/up/stage2.image
    - run: make -kj3 artifacts/up/stage1.image
    - run: make -kj3 build/linux.image.macho
    - run: make -kj3 build/stage2.image.macho
    - run: make -kj3 build/stage1.image.macho
    - run: make -kj3 artifacts/up/linux.image.macho
    - run: make -kj3 artifacts/up/stage2.image.macho
    - run: make -kj3 artifacts/up/stage1.image.macho
    - run: make -kj3 build/m1n1.macho
    - run: make -kj3 build/m1n1.macho.image
    - run: make -kj3 artifacts/up/m1n1.macho
    - run: make -kj3 artifacts/up/m1n1.macho.image
    - run: make -kj3 artifact-push!
