name: workflow
on:
  push:
    branches: [ main, pearl ]
  pull_request:
    branches: [ main, pearl ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: apt-get install gcc-aarch64-linux-gnu
    - run: apt-get install binutils-aarch64-linux-gnu
    - run: make build/linux.image
